""" Defaults
    source $VIMRUNTIME/defaults.vim
    " Stop assuming that I care about C header files
    set path-=/usr/include

    " Disable netrw
    let g:loaded_netrw       = 1
    let g:loaded_netrwPlugin = 1

""" Colors
    colorscheme minimal

""" Appearance
    set cmdheight=1
    set showmode
    set rulerformat=%25(%l,%c%V%M%=%P\ %y%)
    set scrolloff=3
    set sidescrolloff=2
    set showmatch
    set signcolumn=number
    set hlsearch
    set shortmess+=s

""" Behavior
    set noswapfile
    set updatetime=250
    set foldenable
    set foldmethod=indent
    set foldlevelstart=99       " start with all folds opened
    set foldcolumn=0
    set mouse=nv                " enable mouse in normal and visual mode
    set autoread
    set hidden
    set ignorecase              " ignore case in searches ...
    set smartcase               " ... unless it includes capital letters
    set tagcase=match           " ... but match case in :tag searches
    set splitright              " open vertical splits on the right
    set sessionoptions+=options " save global mappings and options
    set completeopt=menuone,noinsert,noselect

""" Special characters
    set list
    set listchars=
    set listchars+=tab:>-
    set listchars+=trail:-
    set listchars+=extends:>
    set listchars+=precedes:<
    set listchars+=nbsp:+

""" Text formatting
    set smarttab
    set tabstop=4
    set shiftwidth=0
    set softtabstop=-1          " use the value of 'shiftwidth'
    set expandtab               " spaces instead of tabs

    set nowrap
    set linebreak
    set breakindent             " indent wrapped lines
    let &showbreak = '... '     " prepend wrapped lines with this
    set smartindent

    set formatoptions=
    set formatoptions+=c        " wrap comments
    set formatoptions+=j        " remove commentstring when joining comment lines
    set formatoptions+=l        " don't wrap lines that were too long to begin with
    set formatoptions+=n        " recognize numbered lists
    set formatoptions+=q        " also format comments with 'gq'
    set formatoptions+=r        " continue comments when hitting <Enter>
    set nojoinspaces            " keep single spaces after sentences

""" Completions
    set wildmode=longest:full,full
    set wildignore=*/node_modules/*
    set wildoptions=pum

""" External programs
    if executable('rg')
        set grepprg=rg\ --vimgrep
        set grepformat=%f:%l:%c:%m
    endif

""" Commands
    " Open a scratch buffer
    command Scratch 10split SCRATCH | setlocal buftype=nofile bufhidden=hide noswapfile

    " Free all quickfix lists
    command Cfree call setqflist([], 'f')
    " Create a new quickfix list to be filled with an quickfix-add command
    command -nargs=? Cnew call setqflist([], ' ', {'nr': '$', 'title': '<args>' == '' ? strftime('%a %r') : '<args>'})

""" Mappings
    " Backspace clears search highlights and updates diffs
    nnoremap <c-l> <cmd>nohlsearch<bar>diffupdate<cr><c-l>

    " Space toggles folds
    nnoremap <space> za

    " Make Y behave like C and D
    nnoremap Y y$

    " Yank to system clipboard with
    noremap "" "+

    " Repetition
    vnoremap . :normal .<cr>
    nnoremap Q @q
    vnoremap Q :normal @q<cr>

    " Cycling lists
    nnoremap <silent> ]a <cmd>next<cr>
    nnoremap <silent> [a <cmd>previous<cr>

    nnoremap <silent> ]b <cmd>bnext<cr>
    nnoremap <silent> [b <cmd>bprevious<cr>

    nnoremap <silent> ]q <cmd>cnext<cr>
    nnoremap <silent> [q <cmd>cprevious<cr>

    nnoremap <silent> ]l <cmd>lnext<cr>
    nnoremap <silent> [l <cmd>lprevious<cr>

    " Make it easier to leave terminal mode
    tnoremap <c-\><c-\> <c-\><c-n>

    " Cycle through quickfix history
    autocmd Filetype qf nnoremap <buffer> < <cmd>colder<cr>
    autocmd Filetype qf nnoremap <buffer> > <cmd>cnewer<cr>
