[colors.primary]
background = "#181818"
foreground = "#d8d8d8"

[colors.normal]
black = "#000000"
red = "#ab4642"
green = "#a1b56c"
yellow = "#f7ca88"
blue = "#7cafc2"
magenta = "#ba8baf"
cyan = "#86c1b9"
white = "#bfbfbf"

[colors.bright]
black = "#404040"
red = "#dc9656"
green = "#282828"
yellow = "#383838"
blue = "#b8b8b8"
magenta = "#e8e8e8"
cyan = "#a16946"
white = "#ffffff"
