[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.normal]
black = "#000000"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#bfbfbf"
yellow = "#e5c07b"

[colors.bright]
black = "#404040"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#e5c07b"
