[colors.bright]
black = "#bfbfbf"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#e45649"
white = "#000000"
yellow = "#c18401"

[colors.normal]
black = "#ffffff"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#e45649"
white = "#404040"
yellow = "#c18401"

[colors.primary]
background = "#f0f0f0"
foreground = "#383a42"
