[colors.bright]
black = "#bdb6a3"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#000000"
yellow = "#657b83"

[colors.normal]
black = "#fdf6f9"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#455b63"
yellow = "#b58900"

[colors.primary]
background = "#fdf6e3"
foreground = "#657b83"
