[colors.primary]
background = "#002b36"
foreground = "#839496"

[colors.normal]
black = "#001b26"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#a3b4b6"
yellow = "#b58900"

[colors.bright]
black = "#294752"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#c3d4d6"
yellow = "#657b83"
