CompileFlags:
  Add:
    - -Werror
    - -Wall
    - -Wextra
    - -Weverything
    - -pedantic
    - -Wno-padded
    - -Wno-shadow
    - -Wno-declaration-after-statement
    - -Wno-strict-prototypes
    - -Wno-gnu-empty-initializer
