#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"

trap 'rm -f "$$.tags.lib"' EXIT

# Typescript dependencies
find . -name '*.d.ts' -path '*/node_modules/*' | ctags --tag-relative=no --sort=yes -L - -f".git/hooks/$$.tags.lib"

mv ".git/hooks/$$.tags.lib" tags.lib
