#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"

trap 'rm -f "$$.tags"' EXIT

git ls-files | ctags --tag-relative=no --sort=yes --languages=-JSON,-Markdown,-SVG,-JavaScript -L - -f"$$.tags"

mv "$$.tags" tags
