#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"

trap 'rm -f "$$.tags.lib"' EXIT

# Typescript dependencies
find . -name '*.d.ts' -path '*/node_modules/*' | ctags --tag-relative=yes --sort=yes -L - -f"$$.tags-lib"

mv "$$.tags-lib" tags-lib
