[general]
import = ["~/.config/alacritty/colors/zenburn.toml"]

[window]
option_as_alt = "OnlyLeft"

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/bash"

[font]
size = 16
normal.family = "Iosevka Nerd Font Mono"
bold.style = "Bold"
italic.style = "Italic"
bold_italic.style= "Bold Italic"

[[keyboard.bindings]]
key = "U"
mode = "Vi"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "D"
mode = "Vi"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "Q"
mode = "Vi"
action = "ToggleViMode"
