#!/bin/bash

repo='cloud-sdk-cosmic'
target='/etc/apt/sources.list.d/google-cloud-sdk.list'

test -f "$target" && grep -F "$repo" "$target" || echo "deb http://packages.cloud.google.com/apt $repo main" | sudo tee -a "$target"

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

apt-get update && apt-get install google-cloud-sdk kubectl
